[package]
name = "unarchiver"
version = "0.1.0"
authors = ["Jess 3Jane <me@jess.coffee>"]

[dependencies]
tar = "0.4"
flate2 = {version = "1.0", features = ["rust_backend"], default-features = false}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
